#!/usr/bin/env python

from __future__ import print_function
from functools import partial
import sys
import math

verbose = False

class UserError(Exception):
  pass

# from http://code.activestate.com/recipes/577452-a-memoize-decorator-for-instance-methods/
class memoize(object):
  def __init__(self, func):
    self.func = func
    
  def __get__(self, obj, objtype=None):
    if obj is None:
      return self.func
    return partial(self, obj)
  
  def __call__(self, *args, **kw):
    obj = args[0]
    try:
      cache = obj.__cache
    except AttributeError:
      cache = obj.__cache = {}
    key = (self.func, args[1:], frozenset(kw.items()))
    try:
      res = cache[key]
    except KeyError:
      res = cache[key] = self.func(*args, **kw)
    return res

def average(list):
  return sum(list)/len(list)

def percentile_to_value(list, *percentiles):
  list = sorted(list)
  return [list[int(p / 100.0 * (len(list)-1))] for p in percentiles]

def variance(list):
  m = average(list)
  return sum([(i-m)**2 for i in list]) / float(len(list))

def std_deviation(list):
  return math.sqrt(variance(list))

class Vector(object):
  def __init__(self, x, y, z):
    self.x, self.y, self.z = x, y, z
  def __str__(self):
    return "(" + str(self.x) + ", " + str(self.y) + ", " + str(self.z) + ")"      

  def __getitem__(self, key):
    if key == 0:
      return self.x
    elif key == 1:
      return self.y
    elif key == 2:
      return self.z
    else:
      raise Exception("Invalid key")
      
  def magnitude(self):
    return math.sqrt(self.x**2 + self.y**2 + self.z**2)
    
Axes = range(3)

class Calibration:
  def __init__(self, values, raw_readings=None):
    self.values = values
    self.raw_readings = raw_readings

  def scale(self, raw_reading):
    return Vector((raw_reading[0] - self.values[0])/float(self.values[1] - self.values[0]) * 2 - 1,
      (raw_reading[1] - self.values[2])/float(self.values[3] - self.values[2]) * 2 - 1,
      (raw_reading[2] - self.values[4])/float(self.values[5] - self.values[4]) * 2 - 1)

  def __str__(self):
    return "%d %d %d %d %d %d" % tuple(self.values)

  def info_string(self):
    return "%-32s %7.4f %7.4f %7.4f" % (
      str(self),
      average(self.scaled_magnitudes()),
      std_deviation(self.scaled_magnitudes()),
      self.score()
    )
    
  def switch_readings(self, raw_readings):
    return Calibration(self.values, raw_readings)
  
  @memoize
  def scaled_magnitudes(self):
    return [s.magnitude() for s in self.scaled_readings()]
    
  @memoize
  def scaled_readings(self):
    return [self.scale(r) for r in self.raw_readings]
  
  @memoize
  def score(self):
    return -average([(m - 1.0)**2 for m in self.scaled_magnitudes()])
  
  def increment(self, value_id, dir):
    values = list(self.values)
    values[value_id] += dir
    return Calibration(values, self.raw_readings)
    
  
def run(file=sys.stdin):
  try:
    print("Reading data...", end="", file=sys.stderr)
    raw_readings = read_vectors(file)
 
    print(" done.", file=sys.stderr) 
    print("Optimizing calibration...", end="", file=sys.stderr)
    raw_readings_sample = raw_readings[0::(len(raw_readings)/300)]
    cal1 = guess(raw_readings)
    cal2 = tune(cal1, raw_readings_sample)
    cal3 = tune(cal2, raw_readings)
    print(" done.", file=sys.stderr)
  
    print(cal3)

  except UserError as e:
    print("Error: " + str(e), file=sys.stderr)

  except KeyboardInterrupt:
    print("", file=sys.stderr)   # newline to tidy things up
    pass

def read_vectors(file):
  vectors = [Vector(*[int(s) for s in line.split()[0:3]]) for line in file]
  # If len(vectors)<300, we get an error in raw_readings[0::(len(raw_readings)/300)] above.
  if len(vectors) < 300:
    raise UserError("Only " + str(len(vectors)) + " readings were provided.  Please provide at least 300.")
  return vectors

def guess(readings):
  guess = []
  for axis in Axes:
    values = [v[axis] for v in readings]
    guess.extend(percentile_to_value(values, 1, 99))
  return Calibration(guess)

def try_dir(cal, value_id, dir):
  improved_cal = None
  while True:
    new_cal = cal.increment(value_id, dir)
    if not new_cal.score() > cal.score():
      return improved_cal
    improved_cal = cal = new_cal
  return None
  
def tune(cal, readings):
  cal = cal.switch_readings(readings)

  if verbose:
    print(cal.info_string(), file=sys.stderr)

  while True:
    last_cal = cal
    
    for value_id in range(len(cal.values)):
      cal = try_dir(cal, value_id, 1) or try_dir(cal, value_id, -1) or cal

    if verbose:
      print(cal.info_string(), file=sys.stderr)

    if last_cal == cal:
      return cal 
    
  
  
if __name__=='__main__':
  run()
